### ISSUE TITLE
How to reimplement same performance？

### ISSUE THREAD

**Issue by AsuradaYuci** [haochenheheda/NFormer#4]
The description in the paper is “**During the inference, the interactions between the different query images are eliminated for fair comparison.** ” But this issue doesn't seem to be considered in the released test code.

**Comment by haochenheheda** [comment]
You can infer with each query image respectively. Here we include all the images for convenience since we already get the whole query set.

**Comment by AsuradaYuci** [comment]
@haochenheheda Thanks for your quick reply. 😭 So what kind of test method was used to obtain such a high result in the paper? I am very interested.

**Comment by haochenheheda** [comment]
In this repo, we concatenate all the query features N1 * C and all the gallery features N2 * C to a feature of shape (N1+N2) * C, and then interact them within one forward pass https://github.com/haochenheheda/NFormer/blob/c78cb848c6b8cf64e973a1ee0ce14488d4904f8f/utils/reid_metric.py#L75-L79
In this manner, you should obtain about 91 mAP on market-1501 dataset.

As for the setting you mentioned above, you could concatenate each query feature 1 * C with all the gallery feature N2 * C and get a feature of shape (1+N2) * C for every query image. Then you can feed them to NFormer respectively. It will take a long time for the inference because we have to infer N1 times instead of 1. The performance should be quite similar to the first method.

**Comment by AsuradaYuci** [comment]
@haochenheheda Thanks, I will have a try.
